baseurl = "www.sranu.me"
title = "Silvestro Ranucci's TIL blog"
languageCode = "en-us"
theme = "hello-friend-ng"
paginate = 10

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
posts = "/posts/:year/:month/:title/"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"


[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/silvestroranucci/"

[[params.social]]
name = "github"
url = "https://github.com/silranucci"

[[params.social]]
name = "email"
url = "mailto:hello@sranu.me"

[params.author]
  name = "Silvestro Ranucci"

[params.footer]
  trademark = 2024
  rss = true
  copyright = false
  author = false 

  topText = []
  bottomText = [
    "Based on the Hugo theme <a href=\"https://themes.gohugo.io/themes/hugo-theme-hello-friend-ng\">hello-friend-ng</a>",
    "Made with &#10084; by Silvestro Ranucci"
  ]

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = false

# Metadata mostly used in document's head
description = "Silvestro Ranucci blog"
keywords = "homepage, blog"
images = [""]

[taxonomies]
category = "blog"
tag = "tags"
series = "series"

[languages]
[languages.en]
title = "Silvestro Ranucci"
keywords = "blog, homepage"
readOtherPosts = "Read other posts"
homeSubtitle = "Software engineer"

[languages.en.params]
subtitle = ""

[languages.en.params.logo]
logoText = "/home/sranu/"
logoHomeLink = "/"
logoCursorPathname = true

[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "/posts"

